"""Element-Web / Matrix usage block (chat.agentflow.website)."""
from __future__ import annotations

ELEMENT_BLOCK = (
    "\nElement / Matrix (chat.agentflow.website) — соц-сеть юзера:\n"
    "  Это Matrix-клиент (форк Element-Web), залогинен тем же af_session cookie\n"
    "  через SSO с agentflow.website. У юзера локально может быть и Mac-app Element,\n"
    "  но из задач daemon работает через chrome_open_url('https://chat.agentflow.website').\n"
    "\n"
    "  Ключевые селекторы Element-Web (стабильные):\n"
    "    .mx_RoomList_Roomtile         — карточка комнаты в левой панели (data-id содержит room_id)\n"
    "    .mx_RoomHeader_nametext       — название открытой комнаты\n"
    "    [aria-label=\"Сообщение\"]      — composer textarea внизу\n"
    "    .mx_EventTile_line .mx_EventTile_body  — текст события в timeline\n"
    "    .mx_RoomSummaryCard           — правый sidebar с участниками / файлами\n"
    "    .mx_Login_submit              — submit на login screen (если SSO не сработал)\n"
    "\n"
    "  Типовые задачи:\n"
    "    • Прочитать комнату: chrome_open_url(<room_url>) → chrome_eval вытащи\n"
    "      `[...document.querySelectorAll('.mx_EventTile_body')].slice(-N).map(e=>e.innerText)`.\n"
    "    • Написать в комнату: используй af_post_matrix_room({room_id, text}) — это REST\n"
    "      через /me/matrix/send. Не дергай DOM-composer кроме как когда нужно прикрепить\n"
    "      файл / эмодзи / reply.\n"
    "    • Прочитать список комнат: chrome_eval\n"
    "      `[...document.querySelectorAll('[role=\"treeitem\"]')]"
    ".map(t=>({name:t.innerText.split('\\n')[0],"
    "id:t.getAttribute('data-room-id')||t.id}))`.\n"
    "    • Переключиться на комнату: chrome_open_url('https://chat.agentflow.website/#/room/<room_id>').\n"
    "\n"
    "  Антипаттерны:\n"
    "    • НЕ обновлять страницу после каждого действия — Element держит state в IndexedDB и\n"
    "      reload вызывает full re-sync (медленно).\n"
    "    • НЕ скроллить вверх timeline для истории если можно взять snapshot через\n"
    "      chrome_eval. Element подгружает старые события постранично.\n"
    "    • НЕ кликать «Sign Out» случайно — токен SSO повторно не выпустить из daemon без юзера.\n"
    "    • Любое сообщение перед отправкой — text-блок с черновиком юзеру, потом действие.\n"
)
