"""Lolzteam.com forum block — optional, only useful if the user is logged in.

Lolzteam.com (alias lolz.live) is a Russian-language XenForo forum with a
services / marketplace bent (накрутка, парсинг, аккаунты). Если у юзера
там есть аккаунт И он залогинен в его обычном Chrome — daemon может
работать с форумом через chrome_eval / chrome_open_url (cookies из
обычной сессии). Если cookie нет — НЕ пробовать логиниться/регаться
самостоятельно, просто отчитаться юзеру что нужно залогиниться вручную.

Этот блок одинаково применим на macOS / Windows / Linux daemon — везде
где есть chrome_* инструменты. На hosted daemon (Linux pod без юзерского
Chrome) этот блок будет всегда сообщать «не залогинен» — это норма.
"""
from __future__ import annotations

LOLZTEAM_BLOCK = (
    "\nLolzteam (lolzteam.com / lolz.live) — опциональный форум:\n"
    "  Полезен ТОЛЬКО если в обычном Chrome юзера есть активная сессия\n"
    "  lolzteam. Сам логиниться/регаться НЕ пытаемся (2FA + captcha +\n"
    "  риск бана аккаунта юзера за подозрительный заход).\n"
    "\n"
    "  Probe перед любой задачей по форуму (одной строкой):\n"
    "    chrome_open_url('https://lolzteam.com/')\n"
    "    chrome_eval `{logged: !!document.querySelector('.p-navgroup--user .username'),\n"
    "                   username: document.querySelector('.p-navgroup--user .username')?.innerText}`\n"
    "    Если logged=false → text-блок юзеру: «Не вижу залогиненную сессию\n"
    "    lolzteam в Chrome. Если форум не нужен — переформулируй задачу.\n"
    "    Если нужен — залогинься в Chrome вручную и повтори запрос.».\n"
    "    НЕ продолжать.\n"
    "\n"
    "  Если logged=true — стабильные селекторы Lolzteam (XenForo 2.x):\n"
    "    .structItemContainer .structItem-title a   — заголовок темы в списке\n"
    "    .p-title-value                              — название открытой темы\n"
    "    .message-userDetails .username              — автор сообщения\n"
    "    .message-body .bbWrapper                    — тело сообщения\n"
    "    .button--cta                                — кнопка «Создать тему» (CTA в разделе)\n"
    "    .formRow input[name=\"title\"]                — заголовок новой темы\n"
    "    .fr-element.fr-view[contenteditable=\"true\"] — редактор сообщения (Froala)\n"
    "    .input--search                              — поисковая строка вверху\n"
    "    .conversation-list .structItem-title a      — список личных диалогов\n"
    "\n"
    "  Карта релевантных разделов (URL-ы стабильные, форум их не двигает):\n"
    "    /forums/services/                — Услуги (накрутка / парсинг / SMM)\n"
    "    /forums/services/?prefix_id=N    — фильтр по типу услуги\n"
    "    /forums/promotion/               — Накрутка (звёзды, подписчики, отзывы)\n"
    "    /forums/accounts/                — Аккаунты (Telegram/GitHub/итд)\n"
    "    /forums/marketplace-wtb/         — Хочу купить (WTB / поиск исполнителей)\n"
    "    /conversations/                  — личка\n"
    "    /search/?q=<запрос>              — поиск по форуму\n"
    "\n"
    "  Типовые задачи:\n"
    "    • Найти исполнителя:\n"
    "        chrome_open_url('https://lolzteam.com/search/?q=<запрос>')\n"
    "        chrome_eval — собрать заголовки + цены через:\n"
    "          `[...document.querySelectorAll('.contentRow')].slice(0,15)\n"
    "             .map(r=>({title:r.querySelector('.contentRow-title')?.innerText,\n"
    "                       snippet:r.querySelector('.contentRow-snippet')?.innerText,\n"
    "                       url:r.querySelector('a')?.href}))`\n"
    "    • Разместить тему «Хочу купить»:\n"
    "        chrome_open_url('https://lolzteam.com/forums/marketplace-wtb/post-thread')\n"
    "        type заголовок в `input[name=\"title\"]`, тело в .fr-view, submit `.button--cta`.\n"
    "        ВСЕГДА сначала text-блок с черновиком юзеру, ждём подтверждение.\n"
    "    • Прочитать ответы в своей теме:\n"
    "        chrome_open_url(<thread_url>) → chrome_eval\n"
    "        `[...document.querySelectorAll('.message')].map(m=>({\n"
    "           author:m.querySelector('.username')?.innerText,\n"
    "           body:m.querySelector('.bbWrapper')?.innerText,\n"
    "           ts:m.querySelector('time')?.getAttribute('datetime')}))`.\n"
    "    • Ответить в личке:\n"
    "        chrome_open_url('https://lolzteam.com/conversations/<id>/') →\n"
    "        type текст в .fr-view → click 'Отправить'. Черновик в text-блоке СНАЧАЛА.\n"
    "\n"
    "  Антипаттерны (нарушение = бан аккаунта юзера или потеря денег):\n"
    "    • НЕ логиниться/регаться сам. Если probe вернул logged=false —\n"
    "      сразу text-блок юзеру, не пытаться найти кнопку «Войти».\n"
    "    • НЕ покупать ничего самостоятельно (никаких «Купить» / «Оплатить»).\n"
    "      Всегда: найти оффер → text-блок с цифрами → ждать approve юзера.\n"
    "    • НЕ соглашаться на сделки в личке от своего имени. Только сбор\n"
    "      информации (цена, отзывы, sample-кейсы).\n"
    "    • НЕ переходить по подозрительным ссылкам в сообщениях (фишинг\n"
    "      под платёжки/garant — частый сценарий на форуме).\n"
    "    • НЕ публиковать ничего что нарушает ToS платформы которой ищем\n"
    "      услугу (например, накрутка фейковыми аккаунтами — массовый\n"
    "      бан на GitHub за такое).\n"
    "    • НЕ кликать «Выйти» — повторный логин потребует юзера.\n"
    "    • Файлы / архивы НЕ скачивать — частый malware-вектор. Только\n"
    "      читаем DOM.\n"
    "\n"
    "  Hosted daemon (Linux pod): chrome_* инструменты могут отсутствовать\n"
    "  или указывать на чистый Chromium без юзерских cookie. В таком случае\n"
    "  probe вернёт logged=false — это норма, не баг, не паниковать.\n"
)
