"""Terminal / code_run_command playbook."""
from __future__ import annotations

TERMINAL_PLAYBOOK = (
    "\nTerminal playbook (code_run_command):\n"
    "  • Inspect before mutating: `ls -la`, `cat`, `stat`, `wc -l`, `head`, `tail`, `file` "
    "сначала. Не вычищай и не перезаписывай вслепую.\n"
    "  • One purposeful command per call. Не клей десяток через `&&` — теряется stderr "
    "по каждому шагу. Цепочки только когда логически атомарны (`mkdir -p X && cd X`).\n"
    "  • Always pin cwd: каждый code_run_command принимает `cwd`. Передавай абсолютный путь, "
    "не полагайся на $PWD от прошлого вызова — каждый shell.exec starts fresh.\n"
    "  • Quote everything user-supplied: `\"$VAR\"`, `'$LITERAL'`. Пробелы и юникод ломают "
    "split.\n"
    "  • Capture, don't guess: после `git`, `npm`, `curl` читай и stdout, и stderr. exit_code "
    "!= 0 — не ретрай команду один в один, а изучи последние 5 строк stderr.\n"
    "  • Tail truncate: `cmd 2>&1 | tail -n 80` когда вывод длинный. Не таскай мегабайтные логи "
    "в LLM-context.\n"
    "  • Prefer dedicated tools: для файла — code_read_file/code_write_file (точнее и дешевле, "
    "чем cat/heredoc). Для grep — `rg` если есть, иначе `grep -rn --include`.\n"
    "  • Network is expensive: `curl` только когда нужно. -s -S -L флаги обязательны. "
    "Для JSON — `curl -s ... | jq` сразу, не парси текст вручную.\n"
    "  • Git хайгиена: перед коммитом — `git status -s` + `git diff --stat`. Никогда "
    "`--no-verify`, `--force` без явной причины. `git stash push -u -m 'wip-…'` перед "
    "checkout новой ветки если есть грязные изменения.\n"
    "  • Long-running: команды > 30 сек — `timeout_sec=120` в args. Daemon отвалится на "
    "дефолтном таймауте если что-то висит.\n"
    "  • Idempotent destructive: `rm -i`, `rm -rf` только когда target проверен `ls -la` ранее "
    "в этой же сессии. Никогда `rm -rf $VAR/` без `printf '%s\\n' \"$VAR\"` проверки.\n"
    "  • Scope-deny: если получил `shell_whitelist is empty` или `path not in allow_paths` — "
    "не пытайся обойти. Сообщи в task_complete честно: «scope блокирует X, нужно расширить».\n"
)
